server:
  port: 8088
spring:
  activiti:
    db-history-used: true #检测历史表是否存在
    check-process-definitions: false # 自动部署验证设置:true-开启（默认）、false-关闭
    history-level: full  #历史表日志级别
    database-schema-update: true  #自动建表

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sp_activiti7?characterEncoding=utf-8&useSSL=true
    username: root
    password: root

logging:
  level:
    org.activiti.engine.impl.persistence.entity: debug